"""Create feedback and parses models

Revision ID: 30f726986983
Revises: 
Create Date: 2020-12-08 17:53:06.042341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f726986983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nl', sa.Unicode(length=500), nullable=False),
    sa.Column('system_lin', sa.Unicode(length=500), nullable=True),
    sa.Column('correct_lin', sa.Unicode(length=500), nullable=True),
    sa.Column('model', sa.Unicode(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nl', sa.Unicode(length=500), nullable=False),
    sa.Column('lin', sa.Unicode(length=500), nullable=False),
    sa.Column('model', sa.Unicode(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nl', 'lin', 'model', name='unique_nl_lin_model')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parses')
    op.drop_table('feedback')
    # ### end Alembic commands ###
